from numpy import *

a = arange(4) # array range
print("a:", a) # array([ 0, 1, 2, 3])

a = arange(0, 4.0, 0.5) # array range 從0至小於4，每次增加0.5
print("a:", a) # array([ 0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

a[0] = 5 # change the 0th element of a to 5
print("a:", a) # array([ 5. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])
                      #  0th  1st  2nd  3rd  4th  5th  6th  7th = -1th
                      #        ^   --------------------->
b = array(range(10)) # b is an array from a list generated by range(10)
print("b:", b) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

c = a[1:-1] **2 # from the 1st to before the last element, generate a new array with squared value
print("c:", c) # array([ 0.25, 1. , 2.25, 4. , 6.25, 9. ])

a[-1] = 100 # change the last element (-1) to 100
print("a:", a) # array([ 5. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 100. ])
                                                #  ^   ------> 
a[5:] *= 0.5 # from the 5th element to the end, change each of them by multiplying 0.5
print("a:", a) # array([ 5. , 0.5 , 1. , 1.5 , 2. , 1.25, 1.5 , 50. ])

c = a[:-1] + b[-7:] # add array a from 0th to before the last element by array b from the last 7th
print("c:", c) # array([ 8. , 4.5 , 6. , 7.5 , 9. , 9.25, 10.5 ]) # element to the end, and generate a new array to store the values

# a = [5. , 0.5 , 1. , 1.5 , 2. , 1.25, 1.5 , 50.] 從0th開始加到倒數第二個
#      ^    ----------------------------->
# b = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 從後方數回去第7個然後依序往後至最後一個
#               ^  --------------->
# c = [8. , 4.5 , 6. , 7.5 , 9. , 9.25, 10.5]